service: aws-python-simple-http-endpoint

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.6 # or python3.7, supported as of November 2018
plugins:
   - serverless-python-requirements

custom:
  pythonRequirements:
     dockerizePip: non-linux
functions:
  wikiPageInfo:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get